### PR TITLE
Update flask

### PR DESCRIPTION
**Pull request by boriscosic**

### CODE REVIEW

**Comment by boriscosic** [comment]
:star: PR built and available in a preview environment **atb-leap-boilerplate-cloud-functions-pr-4** [here](http://boilerplate-cloud-functions.jx-atb-leap-boilerplate-cloud-functions-pr-4.35.203.123.59.nip.io)

**Comment by ghost** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/atb-leap/boilerplate-cloud-functions/pull/4#issuecomment-532234458" title="Approved">boriscosic</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=atb-leap%2Fboilerplate-cloud-functions).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/atb-leap/boilerplate-cloud-functions/blob/master/OWNERS)~~ [boriscosic]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ghost** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/atb-leap/boilerplate-cloud-functions/pull/4#issuecomment-532234458" title="Approved">boriscosic</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=atb-leap%2Fboilerplate-cloud-functions).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/atb-leap/boilerplate-cloud-functions/blob/master/OWNERS)~~ [boriscosic]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ghost** [comment]
@boriscosic: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
serverless-jenkins | da98bd08a2421b423593005314bbd9b0bd2095f2 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Pull request merged**
